import { CharType, Registry } from '@/core'

Registry.text.register({
  key: 'FourCharIdioms',
  title: '四字成语',
  description: '常用四字成语练习',
  text: [
    { type: CharType.Hanzi, char: '一', quanpin: 'yi' },
    { type: CharType.Hanzi, char: '心', quanpin: 'xin' },
    { type: CharType.Hanzi, char: '一', quanpin: 'yi' },
    { type: CharType.Hanzi, char: '意', quanpin: 'yi' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '三', quanpin: 'san' },
    { type: CharType.Hanzi, char: '心', quanpin: 'xin' },
    { type: CharType.Hanzi, char: '二', quanpin: 'er' },
    { type: CharType.Hanzi, char: '意', quanpin: 'yi' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '七', quanpin: 'qi' },
    { type: CharType.Hanzi, char: '上', quanpin: 'shang' },
    { type: CharType.Hanzi, char: '八', quanpin: 'ba' },
    { type: CharType.Hanzi, char: '下', quanpin: 'xia' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '十', quanpin: 'shi' },
    { type: CharType.Hanzi, char: '全', quanpin: 'quan' },
    { type: CharType.Hanzi, char: '十', quanpin: 'shi' },
    { type: CharType.Hanzi, char: '美', quanpin: 'mei' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '百', quanpin: 'bai' },
    { type: CharType.Hanzi, char: '发', quanpin: 'fa' },
    { type: CharType.Hanzi, char: '百', quanpin: 'bai' },
    { type: CharType.Hanzi, char: '中', quanpin: 'zhong' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '千', quanpin: 'qian' },
    { type: CharType.Hanzi, char: '军', quanpin: 'jun' },
    { type: CharType.Hanzi, char: '万', quanpin: 'wan' },
    { type: CharType.Hanzi, char: '马', quanpin: 'ma' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '万', quanpin: 'wan' },
    { type: CharType.Hanzi, char: '众', quanpin: 'zhong' },
    { type: CharType.Hanzi, char: '一', quanpin: 'yi' },
    { type: CharType.Hanzi, char: '心', quanpin: 'xin' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '春', quanpin: 'chun' },
    { type: CharType.Hanzi, char: '暖', quanpin: 'nuan' },
    { type: CharType.Hanzi, char: '花', quanpin: 'hua' },
    { type: CharType.Hanzi, char: '开', quanpin: 'kai' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '风', quanpin: 'feng' },
    { type: CharType.Hanzi, char: '和', quanpin: 'he' },
    { type: CharType.Hanzi, char: '日', quanpin: 'ri' },
    { type: CharType.Hanzi, char: '丽', quanpin: 'li' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '鸟', quanpin: 'niao' },
    { type: CharType.Hanzi, char: '语', quanpin: 'yu' },
    { type: CharType.Hanzi, char: '花', quanpin: 'hua' },
    { type: CharType.Hanzi, char: '香', quanpin: 'xiang' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '山', quanpin: 'shan' },
    { type: CharType.Hanzi, char: '清', quanpin: 'qing' },
    { type: CharType.Hanzi, char: '水', quanpin: 'shui' },
    { type: CharType.Hanzi, char: '秀', quanpin: 'xiu' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '海', quanpin: 'hai' },
    { type: CharType.Hanzi, char: '阔', quanpin: 'kuo' },
    { type: CharType.Hanzi, char: '天', quanpin: 'tian' },
    { type: CharType.Hanzi, char: '空', quanpin: 'kong' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '学', quanpin: 'xue' },
    { type: CharType.Hanzi, char: '富', quanpin: 'fu' },
    { type: CharType.Hanzi, char: '五', quanpin: 'wu' },
    { type: CharType.Hanzi, char: '车', quanpin: 'che' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '博', quanpin: 'bo' },
    { type: CharType.Hanzi, char: '学', quanpin: 'xue' },
    { type: CharType.Hanzi, char: '多', quanpin: 'duo' },
    { type: CharType.Hanzi, char: '才', quanpin: 'cai' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '勤', quanpin: 'qin' },
    { type: CharType.Hanzi, char: '学', quanpin: 'xue' },
    { type: CharType.Hanzi, char: '苦', quanpin: 'ku' },
    { type: CharType.Hanzi, char: '练', quanpin: 'lian' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '废', quanpin: 'fei' },
    { type: CharType.Hanzi, char: '寝', quanpin: 'qin' },
    { type: CharType.Hanzi, char: '忘', quanpin: 'wang' },
    { type: CharType.Hanzi, char: '食', quanpin: 'shi' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '持', quanpin: 'chi' },
    { type: CharType.Hanzi, char: '之', quanpin: 'zhi' },
    { type: CharType.Hanzi, char: '以', quanpin: 'yi' },
    { type: CharType.Hanzi, char: '恒', quanpin: 'heng' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '锲', quanpin: 'qie' },
    { type: CharType.Hanzi, char: '而', quanpin: 'er' },
    { type: CharType.Hanzi, char: '不', quanpin: 'bu' },
    { type: CharType.Hanzi, char: '舍', quanpin: 'she' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '水', quanpin: 'shui' },
    { type: CharType.Hanzi, char: '滴', quanpin: 'di' },
    { type: CharType.Hanzi, char: '石', quanpin: 'shi' },
    { type: CharType.Hanzi, char: '穿', quanpin: 'chuan' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '绳', quanpin: 'sheng' },
    { type: CharType.Hanzi, char: '锯', quanpin: 'ju' },
    { type: CharType.Hanzi, char: '木', quanpin: 'mu' },
    { type: CharType.Hanzi, char: '断', quanpin: 'duan' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '精', quanpin: 'jing' },
    { type: CharType.Hanzi, char: '益', quanpin: 'yi' },
    { type: CharType.Hanzi, char: '求', quanpin: 'qiu' },
    { type: CharType.Hanzi, char: '精', quanpin: 'jing' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '一', quanpin: 'yi' },
    { type: CharType.Hanzi, char: '丝', quanpin: 'si' },
    { type: CharType.Hanzi, char: '不', quanpin: 'bu' },
    { type: CharType.Hanzi, char: '苟', quanpin: 'gou' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '全', quanpin: 'quan' },
    { type: CharType.Hanzi, char: '力', quanpin: 'li' },
    { type: CharType.Hanzi, char: '以', quanpin: 'yi' },
    { type: CharType.Hanzi, char: '赴', quanpin: 'fu' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '勇', quanpin: 'yong' },
    { type: CharType.Hanzi, char: '往', quanpin: 'wang' },
    { type: CharType.Hanzi, char: '直', quanpin: 'zhi' },
    { type: CharType.Hanzi, char: '前', quanpin: 'qian' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '迎', quanpin: 'ying' },
    { type: CharType.Hanzi, char: '难', quanpin: 'nan' },
    { type: CharType.Hanzi, char: '而', quanpin: 'er' },
    { type: CharType.Hanzi, char: '上', quanpin: 'shang' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '知', quanpin: 'zhi' },
    { type: CharType.Hanzi, char: '难', quanpin: 'nan' },
    { type: CharType.Hanzi, char: '而', quanpin: 'er' },
    { type: CharType.Hanzi, char: '进', quanpin: 'jin' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '无', quanpin: 'wu' },
    { type: CharType.Hanzi, char: '私', quanpin: 'si' },
    { type: CharType.Hanzi, char: '奉', quanpin: 'feng' },
    { type: CharType.Hanzi, char: '献', quanpin: 'xian' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '舍', quanpin: 'she' },
    { type: CharType.Hanzi, char: '己', quanpin: 'ji' },
    { type: CharType.Hanzi, char: '为', quanpin: 'wei' },
    { type: CharType.Hanzi, char: '人', quanpin: 'ren' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '大', quanpin: 'da' },
    { type: CharType.Hanzi, char: '公', quanpin: 'gong' },
    { type: CharType.Hanzi, char: '无', quanpin: 'wu' },
    { type: CharType.Hanzi, char: '私', quanpin: 'si' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '克', quanpin: 'ke' },
    { type: CharType.Hanzi, char: '己', quanpin: 'ji' },
    { type: CharType.Hanzi, char: '奉', quanpin: 'feng' },
    { type: CharType.Hanzi, char: '公', quanpin: 'gong' },
    { type: CharType.Mark, char: '。' },
  ],
})
