import { CharType, Registry } from '@/core'

Registry.text.register({
  key: 'TwoCharWords',
  title: '两字词语',
  description: '常用两字词语练习',
  text: [
    { type: CharType.Hanzi, char: '学', quanpin: 'xue' },
    { type: CharType.Hanzi, char: '习', quanpin: 'xi' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '工', quanpin: 'gong' },
    { type: CharType.Hanzi, char: '作', quanpin: 'zuo' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '生', quanpin: 'sheng' },
    { type: CharType.Hanzi, char: '活', quanpin: 'huo' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '快', quanpin: 'kuai' },
    { type: CharType.Hanzi, char: '乐', quanpin: 'le' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '朋', quanpin: 'peng' },
    { type: CharType.Hanzi, char: '友', quanpin: 'you' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '家', quanpin: 'jia' },
    { type: CharType.Hanzi, char: '庭', quanpin: 'ting' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '美', quanpin: 'mei' },
    { type: CharType.Hanzi, char: '好', quanpin: 'hao' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '希', quanpin: 'xi' },
    { type: CharType.Hanzi, char: '望', quanpin: 'wang' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '梦', quanpin: 'meng' },
    { type: CharType.Hanzi, char: '想', quanpin: 'xiang' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '努', quanpin: 'nu' },
    { type: CharType.Hanzi, char: '力', quanpin: 'li' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '奋', quanpin: 'fen' },
    { type: CharType.Hanzi, char: '斗', quanpin: 'dou' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '成', quanpin: 'cheng' },
    { type: CharType.Hanzi, char: '功', quanpin: 'gong' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '幸', quanpin: 'xing' },
    { type: CharType.Hanzi, char: '福', quanpin: 'fu' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '阳', quanpin: 'yang' },
    { type: CharType.Hanzi, char: '光', quanpin: 'guang' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '春', quanpin: 'chun' },
    { type: CharType.Hanzi, char: '天', quanpin: 'tian' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '花', quanpin: 'hua' },
    { type: CharType.Hanzi, char: '朵', quanpin: 'duo' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '树', quanpin: 'shu' },
    { type: CharType.Hanzi, char: '木', quanpin: 'mu' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '山', quanpin: 'shan' },
    { type: CharType.Hanzi, char: '水', quanpin: 'shui' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '风', quanpin: 'feng' },
    { type: CharType.Hanzi, char: '景', quanpin: 'jing' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '音', quanpin: 'yin' },
    { type: CharType.Hanzi, char: '乐', quanpin: 'yue' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '书', quanpin: 'shu' },
    { type: CharType.Hanzi, char: '籍', quanpin: 'ji' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '知', quanpin: 'zhi' },
    { type: CharType.Hanzi, char: '识', quanpin: 'shi' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '智', quanpin: 'zhi' },
    { type: CharType.Hanzi, char: '慧', quanpin: 'hui' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '勇', quanpin: 'yong' },
    { type: CharType.Hanzi, char: '敢', quanpin: 'gan' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '善', quanpin: 'shan' },
    { type: CharType.Hanzi, char: '良', quanpin: 'liang' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '诚', quanpin: 'cheng' },
    { type: CharType.Hanzi, char: '信', quanpin: 'xin' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '友', quanpin: 'you' },
    { type: CharType.Hanzi, char: '爱', quanpin: 'ai' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '团', quanpin: 'tuan' },
    { type: CharType.Hanzi, char: '结', quanpin: 'jie' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '进', quanpin: 'jin' },
    { type: CharType.Hanzi, char: '步', quanpin: 'bu' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '自', quanpin: 'zi' },
    { type: CharType.Hanzi, char: '由', quanpin: 'you' },
    { type: CharType.Mark, char: '，' },
    { type: CharType.Hanzi, char: '和', quanpin: 'he' },
    { type: CharType.Hanzi, char: '平', quanpin: 'ping' },
    { type: CharType.Mark, char: '。' },
  ],
})
